### ISSUE TITLE
Windows release v1.2.0 does ... nothing?

### ISSUE THREAD

**Issue by mlawren** [Jacalz/wormhole-gui#1]
Running the v1.2.0 executable from wormhole-gui-windows-amd64.zip on a 64-bit Windows 8.1 results in no window or visible application. Should it?

**Comment by mlawren** [comment]
Actually, I have the same problem with your Sparta application - in both cases after the initial "Open File - Security Warning" message from Windows there is nothing. So perhaps this is a local issue...

**Comment by Jacalz** [comment]
Sorry for responding quite late. This seems to have totally flown under my radar :slightly_frowning_face: 
Will try to test this myself on Windows and perhaps get out a new release quite soon.

**Comment by Jacalz** [comment]
The binaries seem to work fine on Windows for me. Would you mind checking out https://github.com/Jacalz/wormhole-gui/releases/tag/v1.3.0 to see if the issue still persists?

**Comment by mlawren** [comment]
Running v1.3.0 produces no visible window for me, however I do see the 
process in the task list. It shows no CPU or disk activity, but
the private resident set memory changed regularly starting from about 
5MB down to 1.5MB.

v1.2.0 did not appear in the tasklist at all.

-- 
Mark Lawrence

**Comment by Jacalz** [comment]
Hmm, that sounds very strange. I am starting to think that this might be an issue with `fyne`. Would you mind giving the windows exe for the fyne demo a test?
[fyne_demo.exe.zip](https://github.com/Jacalz/wormhole-gui/files/5227308/fyne_demo.exe.zip)

**Comment by Jacalz** [comment]
Could it perhaps be that you are missing a graphics driver for your system? Fyne requires an OpenGL driver to function properly.

**Comment by mlawren** [comment]
I see the same behaviour with the fyne demo.

The details of my OpenGL support are hopefully obvious from this screenshot: ![opengl](https://user-images.githubusercontent.com/82904/93423910-2aaf5b80-f8f6-11ea-93f5-b9123929f162.png)

I suspect that OpenGL 1.1 support is a bit too far back in time for fyne to run correctly. So you can probably close this ticket out as "not supported." It would however be nice if fyne (or wormhole-gui) would fail to run more loudly when the system requirements are not met.

**Comment by Jacalz** [comment]
Yeah, I think that this might be a driver issue. I double checked with the team and it looks like `fyne` requires OpenGL 2.0 or later. I would suggest that you try to update the drivers, because the hardware should technically be able to support OpenGL 2.1 if the info that I found is correct.

**Comment by sergeevabc** [comment]
An encryption application that needs OpenGL? Are you kidding? For example, GPG has been running for decades on laptops without a graphics card.

![2024-0201-1435 fyne rymdport opengl](https://github.com/Jacalz/rymdport/assets/373718/2d3758dc-52f0-43c4-8407-9a9416e94117)

**Comment by Jacalz** [comment]
> An encryption application that needs OpenGL? Are you kidding? For example, GPG has been running for decades on laptops without a graphics card.

I don't appreciate the tone and the "Are you kidding?" part. Please do follow the [CODE_OF_CONDUCT.md](https://github.com/Jacalz/rymdport/blob/main/CODE_OF_CONDUCT.md) for the project. 

**Let me clarify some things here:**

Encryption has nothing to do with it. Rymdport is a graphical application, i.e. it shows a window on your desktop and hence the requirement on OpenGL to render that window. There is nothing strange with that.

**Comment by Jacalz** [comment]
If you read through this issue you would see that the OpenGL version required isn't my fault or even part of the application that I built but because of the dependency (fyne, https://github.com/fyne-io/fyne) that I use for creating the user interface. If you wish to add support for older OpenGL versions, then by all means open an issue there. There is nothing I can do here to solve that for you. There is absolutely no reason to direct your hate against me by saying that my application is a failure.

**Comment by sergeevabc** [comment]
The coding stage is preceded by the design stage, where you choose the language, dependencies, etc. And it is you who have chosen to depend on a component that turns the interface into something like a video game, increasing the hardware requirements for no reason. To display a menu, a few lines of text and a couple of buttons, there is no need for OpenGL 2.1. For example, I use the cross-platform text editor [Sublime Text](https://www.sublimetext.com/), which not only runs smoothly and looks beautiful, but also allows me to choose different ways to render fonts (Cleartype, Directwrite, GDI, etc).

In my case, we are talking about a combination of Intel 965 and Intel X3100 chipsets, which use the most updated and tweaked drivers available. The only workaround here is to use Mesa OpenGL emulation by putting [opengl32.dll x64](https://fdossena.com/?p=mesa/index.frag) in the app's folder.

![2024-0201-1435 fyne rymdport opengl mesa](https://github.com/Jacalz/rymdport/assets/373718/c6861f60-2a0b-46a7-9ac1-e505738ba814)

**Comment by Jacalz** [comment]
> The coding stage is preceded by the design stage, where you choose the language, dependencies, etc.

Absolutely. I'm no stranger to designing software but you have to make a tradeoff between what is important. Fyne was the best option at the time for me and my requirements, and probably still is to this day.

I have no intention to work around Intel's terrible old Windows drivers. It wasn't my main priority when designing this software. Everything I can find online does indicate that your hardware actually supports OpenGL 2.1 (https://en.m.wikipedia.org/wiki/Intel_GMA) but, just like what I stated in an earlier comment, it is the drivers that doesn't handle it even through the hardware does. Using Linux will give you all of what the hardware can do. It's a shame that Intel did what they did to that ecosystem on Windows but it is what it is and I can't do much about it.

> And it is you who have chosen to depend on a component that turns the interface into something like a video game, increasing the hardware requirements for no reason. To display a menu, a few lines of text and a couple of buttons, there is no need for OpenGL 2.1. For example, I use the cross-platform text editor Sublime Text, which not only runs smoothly and looks beautiful, but also allows me to choose different ways to render fonts (Cleartype, Directwrite, GDI, etc).

Like I wrote above, your other application running fine is likely because they support DirectX on Windows, something that Intel's old drivers do far better than OpenGL (but Fyne doesn't support). You can't use that as a reference for saying that OpenGL 2.1 is unnecessary. Fyne is using features from that standard because it provides an improvement (I think the sRGB texture feature is used and potentially some better compatibility with reusing the shaders for the GLES backend on mobile). As a relatively new toolkit with cross-platform support, it made a lot more sense to focus on a graphics API that can run on all platforms instead of writing a Windows specific backend and another backend for other systems.


I'm glad that you got it running with software rendering even though it of course isn't perfect. About your screenshot there, what are you running? Windows Vista or Windows 7 perhaps? It is worth noting that the Go 1.21 compiler dropped support for everything older than Windows 10 (https://go.dev/doc/go1.21#windows). The current release of Rymdport supports Go 1.18 as base and the upcoming will bump that to 1.20. The big release after that will likely bump it to 1.21 or 1.22 so older Windows versions will see support removed sooner or later I'm afraid.
