### ISSUE TITLE
Add better design wayfinding, basic explanation of features.

### ISSUE THREAD

**Issue by nfd9001** [Jacalz/wormhole-gui#25]
### Is your feature request related to a problem? Please describe:

Congrats! You've probably made the best tool out there to solve the problem "I want to be able to share files with someone without expertish computer skill, and I want to do it directly, cheaply, securely, and without having to sign up for a bunch of random stuff." In my opinion, anyway :grin:. magic-wormhole could be an amazing tool for this, but trying to talk someone through setting up a CLI client and using it is a non-starter, given the "your users aren't experts" qualification.

I mentioned [wayfinding](https://en.wikipedia.org/wiki/Wayfinding) in the title. Designing for good wayfinding in a physical space (like a building) involves using cues, signs, sightlines, etc. to make it easier for people in the space to figure out how to do what they need to do. ([Here's a fun podcast on that, if that's your wont.](https://99percentinvisible.org/episode/walk-this-way/)) Obviously some of these ideas extend just fine to UIs. So I'm going to tell a little story about trying to send some files with wormhole-gui. Bear in mind that this person has general basic computer literacy and is most of the way through a Master's degree--already probably above the mean when it comes to their ability to figure this all out.

So, say I'm on the phone with someone (in reality, we were sitting in the same room, but I'm asking questions like I would a user talking to another user over the phone) and we need to move some files around. I say "hey, get a Magic Wormhole client, I'll send the file that way." So they google "magic wormhole," and get a Github page. There's no "download" button, and the *best* thing they're going to hear will be something like "go install a Python distribution for your system, set up `pip`, and `pip install` the package." Now, that works great for hackers, but it works terribly for users.

So I say "oh, there's this thing called `wormhole-gui`, try that" over the phone. This user then googles `wormhole gooey` and gets a page full of creepy kids youtube videos and other useless stuff. So I say "oh it's gee you eye, and it has like a dash in the name?" and they search that instead and find this Github repo. 

Great. And then they glance at the page and don't actually immediately know what to do. If they scroll down a little on a typical system, they might see the "Download" section in the readme: that's good! What actually happened this time, though, was that they:
1. tried clicking the "Code" dropdown, which is helpfully bright green, as it's a very important button for developers to be able to press, and got some more confusing text
2. tried clicking "Go To File" in hopes of finding some downloads there (no dice)
3. took my advice of "oh, try clicking the 'Releases' thing in the sidebar on the right," which I understand as the usual convention for this sort of thing, which I just knew because I'm a developer.

Next, they see this big page full of various Stuff, and aren't sure what to do next. I say that they want the file in the list that says it's for "Windows on amd64," which I know because I'm a developer. They download it, click the zip, click the .exe, see a Windows SmartScreen popup, close it, try to run the .exe again, think about it for a second, listen to me saying "yeah, I can vouch, this program is safe," click the little "More info" button, and "Run Anyway." And it's running fine without any other messing-around or install steps! That's great!

Next, they immediately try to send me some random file. They pick some PDF sitting on their drive, click Send, and... can't figure out what to do next. (The filename is long enough that it doesn't show the wormhole code or progress bar, see #24.) So I say "try sending me a text message instead." They write and attempt to send one easily, and then say "I can't figure out who this was sent to." I say "oh, there's a three-word code." They read it off, and I receive the text a few seconds later. Great.

Now it's my turn to send something. I pick a file, click send, and then read off my code. They easily find where to type the code in, do so, and then say "It says that was an invalid code." I say "oh, there's dashes between the words, try that." They receive the file, no problem.

I say "Okay, now go open that file." They click on the file's entry inside `wormhole-gui`, and just get popups asking if they want to remove the file from the list. I say "okay, where else can you look?" and they check their system's Downloads folder, and could then open the file without issue.

### Describe the solution you'd like to see:

`wormhole-gui` is an excellent, descriptive name if you're a hacker. It's a weird one for an end user. A name that's simple, uses plain English, and still gets the message "I can use this to send/get files through 'Magic Wormhole'" across *might* be better. (I think this is part of why `wormhole-william` is a pretty good name, actually: I can tell someone to google it and they're not going to get mixed up with anything else.)

It'd be a good idea to have a basic landing site (with a short name!) that explains what wormhole-gui is ("Quickly and easily send and receive files through the Magic Wormhole"), has immediate visual download buttons for each supported platform, and then other further detail. You could make a simple static site with Github Pages, and give it a snappy name by creating an organization on Github, resulting in a simple URL like `wormhole-gui.github.io` that would be easy to read off over the phone. Two or three birds with one stone. That sort of page doesn't need to be complicated. (You could add a note under the Windows link with something like "You might get a Windows SmartScreen warning when you try to run wormhole-gui for the first time: this is because wormhole-gui doesn't have massive numbers of users, not because it's unsafe.")

There should be some further wayfinding inside wormhole-gui itself. For instance, when you're on the Send pane, you might include some text that says "Choose a file, then give the person you want to send it to its wormhole code, alongside a three-column top bar in the list that reads something like `Filename | Wormhole code | Progress`.

In the receiving section, there should be some text explaining what it is, e.g. "Ask the person sending you a file for its wormhole code, and type it here." The box for inputting wormhole codes should be able to "correct" spaces into dashes. It *may* be nice to add something like `magic-wormhole`'s tab-autocomplete: the rest of the suggested word could appear in grey, and you could put a little tab icon to offer to complete the word. (I could break that last part into its own suggestion if you like.) When you click on a file in the list, it should offer to open in/navigate to it.

**Comment by Jacalz** [comment]
Thanks for the kind words and all the constructive feedback. It is all very useful input and very important for improving the application. There is a lot to take in, so I'll try to the best of my ability to answer as much as possible.

I guess the issues with downloading releases is probably more of an issue with how GitHub is set up and I do understand the problems there. Gitlab is a bit more intuitive in that regard (but let's not discuss differences between GitHub and Gitlab). Having a website is a very good suggestion and something that I have wanted to do in the past (both one for my projects and a personal one). I simply haven't had the time to do it amidst all other things.

The name is a long story and I have really wanted to change it. It made sense in the very early beginning because it was not meant as anything more than a very basic gui for educational purposes. I am open for suggestions for better names but I am also afraid that changing the name could result in people not finding it again if they don't know that the name has changed.

As for wayfinding inside the application, it is a hard thing. I am personally about 1/10 on my way towards a master in Computer Science so I realise that the things that make a lot of sense to me don't necessarily do to others. Adding a lot text is something that I most likely want to avoid. A good user interface should be self descriptive and not need explaining, adding text is usually a workaround for a poor interface. I am personally no master ui/ux guy in that sense and is very open to suggestions, mockups and other ideas for making the interface more intuitive.

Correcting spaces to dashes is a wonderful idea but I'm not 100% sure that it can be done in a good way. I think (but might be wrong) that wormhole codes can contain spaces as part of the message in between the dashes and thus we can't just naïvely replace spaces with dashes. I promise to look in to it, because it would be great if we could.

I unfortunatelly don't think the tab auto complete can be implemented visually with grey text due to limitations inside the Entry widget in the Fyne toolkit. It would require a lot of glue on top that I'm not sure if it is worth maintaining. The tab-autocomplete is a good idea. There could be limitations in wormhole-william as to how this can be done. I will have to look into how the python version does for this and to what extent we can do it here as well.

Hmm, the idea to open or navigate to the file is a good idea but it is most likely going to be an entire nightmare to make it cross platform unfortunatelly. It would require to not only know which file manager is the default on Linux and BSD systems, but also a lot of handling for opening the files in the correct default application on systems. I think it would have to stay as it is sadly.

**Comment by Jacalz** [comment]
What do you think of the name "rosenbridge" or "rosenbro" as a better name?

**Comment by achhabra2** [comment]
@nfd9001 I re-built this app using the wails framework mostly for fun / learning, but then decided to turn it into a thing. Should provide a landing page / slightly easier UX for the casual users. Check it out - https://riftshare.app

**Comment by Jacalz** [comment]
> @nfd9001 I re-built this app using the wails framework mostly for fun / learning, but then decided to turn it into a thing. Should provide a landing page / slightly easier UX for the casual users. Check it out - https://riftshare.app
> 
> 
> 
> 

Don't get me wrong here, I do appreciate that you point to this project as inspiration. However, I must say that I don't appreciate advertising for it in this way. This is an issue about improving the way finding of wormhole-gui and I don't think it is fair to try and use that as an excuse to advertise a competitive project.

**Comment by achhabra2** [comment]
> > @nfd9001 I re-built this app using the wails framework mostly for fun / learning, but then decided to turn it into a thing. Should provide a landing page / slightly easier UX for the casual users. Check it out - https://riftshare.app
> 
> Don't get me wrong here, I do appreciate that you point to this project as inspiration. However, I must say that I don't appreciate advertising for it in this way. This is an issue about improving the way finding of wormhole-gui and I don't think it is fair to try and use that as an excuse to advertise a competitive project.

Fair enough. Did not mean any harm here honestly. You have done great work and I appreciate your contribution to the community. I am just trying to do the same. I don’t view this as a competition, more so in the spirit of libre software.

**Comment by Jacalz** [comment]
> > > @nfd9001 I re-built this app using the wails framework mostly for fun / learning, but then decided to turn it into a thing. Should provide a landing page / slightly easier UX for the casual users. Check it out - https://riftshare.app
> 
> > 
> 
> > Don't get me wrong here, I do appreciate that you point to this project as inspiration. However, I must say that I don't appreciate advertising for it in this way. This is an issue about improving the way finding of wormhole-gui and I don't think it is fair to try and use that as an excuse to advertise a competitive project.
> 
> 
> 
> Fair enough. Did not mean any harm here honestly. You have done great work and I appreciate your contribution to the community. I am just trying to do the same. I don’t view this as a competition, more so in the spirit of libre software. 

No worries and thanks a lot. Just would have appreciated seeing it somewhere else.

**Comment by Jacalz** [comment]
I think this issue is very hard to solve at the current state. The issue has way too much text so fixing everything is going to be hard and so on. It would be better to break up feature requests into separate issues.

I am going to close this but that does not mean that I won't try to improve the user experience going forward. The plan is to probably change the name in the near future. Concrete suggestions (possibly even mockups) on how to make the user interface more easy to use.  Help is always appreciated in any way, shape or form.
